name: CI

# Controls when the action will run.
on:
  pull_request:
    branches: [main]
  workflow_dispatch:

# Allow only one concurrent deployment, skipping runs queued between the run
# in-progress and latest queued. We do not wish to waste time on old runs if a
# newer one is available.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:

  linting:
    uses: ./.github/workflows/check_lint.yml

  UnitTesting:
    uses: ./.github/workflows/check_unit_test.yml

  check_complete:
    name: PR Ready
    needs:
      - linting
      - UnitTesting

    runs-on: ubuntu-latest
    env:
      lint_status: ${{ needs.linting.result }}
      unittest_status: ${{ needs.UnitTesting.result }}
    steps:
      - name: All checks passed
        run: |
          success=true
          fail=()
          if [ "$lint_status" != "success" ]; then
            fail+=("\t- lint check: $lint_status")
            success=false
          fi
          if [ "$unittest_status" != "success" ]; then
            fail+=("\t- unit test check: $unittest_status")
            success=false
          fi
          
          if [ "$success" = false ]; then
            >&2 echo "The following checks failed:"
            for i in "${fail[@]}"; do
              >&2 printf "$i\n"
            done
            exit 1
          fi
          echo "All checks passed"          
