name: CI

# Controls when the action will run.
on:
  pull_request:
    branches: [main]
  workflow_dispatch:

# Allow only one concurrent deployment, skipping runs queued between the run
# in-progress and latest queued. We do not wish to waste time on old runs if a
# newer one is available.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:

  linting:
    uses: ./.github/workflows/check_lint.yml

  UnitTesting:
    uses: ./.github/workflows/check_unit_test.yml

  check_complete:
    name: Main PR Ready
    needs:
      - linting
      - UnitTesting

    runs-on: ubuntu-latest
    steps:
      - name: All checks passed
        run: |
          echo "All checks passed"
          
